create table if not exists public.tracking_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  event_label text,
  url text,
  path text,
  referrer text,
  session_id text,
  user_agent text,
  device_type text,
  country text,
  region text,
  city text,
  ip_hash text,
  payload_json jsonb not null default '{}'::jsonb
);

create index if not exists tracking_events_created_at_idx
  on public.tracking_events (created_at desc);

create index if not exists tracking_events_event_type_idx
  on public.tracking_events (event_type);
