export const CONTACT = Object.freeze({
  email: 'kontakt@talkateria.pl',
  obfuscatedEmail: 'kontakt [at] talkateria.pl',
  phoneNumber: '506 135 219',
  phoneHref: 'tel:+48506135219',
  phoneInternational: '+48 506 135 219',
  addressShort: 'Rumia, ul. Wrocławska 2',
  addressWithOnline: 'Rumia, ul. Wrocławska 2 lub online',
  streetAddress: 'ul. Wrocławska 2',
  addressLocality: 'Rumia',
  addressRegion: 'pomorskie',
  addressCountry: 'PL',
  openingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  lessonHours: '14.00-20.30',
  lessonOpens: '14:00',
  lessonCloses: '20:30',
  contactHours: '8.00-13.00',
  contactOpens: '08:00',
  contactCloses: '13:00',
  lessonHoursText: 'Zajęcia prowadzę w godzinach 14.00-20.30.',
  contactHoursText:
    'Kontakt telefoniczny i SMS najlepiej w godzinach 8.00-13.00.',
  emailResponseText:
    'Maila można wysłać o każdej porze; odpowiadam zwykle w ciągu kilku godzin.',
})
